ami                     = "ami-02a39bdb8e8ee056a "
instance_type           = "t2.micro"
keyname                 = "testkey"
subnet_id               = "subnet-38457f63"
Name                    = "Consul"
